pypy/deploy, python3/deploy
This allows Python3 and Pypy packages to be installed when they don't have a requirements.txt file.
=> Enabling app install when only setup.py is present on Py3 and PyPy

static/deploy, static/validate-nginx-conf
We can later on leverage this script in the CI or on build time on Docker Hub (running validate-nginx-conf as one of the steps of Dockerfile would break the build if we break nginx.conf, but having that
on a CI would be good as well).
Sending as a pull request because I didn't discuss with you guys before doing that :-)
=> static: add script for validating nginx.conf

static/deploy
Just to prevent serving the nginx.conf file.
=> static/deploy: move the configuration file instead of copying it

lua/README.md, lua/deploy
This PR fixes the installation of luarocks and also fixes the default name of the rockspec file that is used to install the dependencies.
=> Fixing how dependencies should work and installation of luarocks

nodejs/deploy
add yarn support to nodejs platform.
user should add a yarn.lock file to their repository in order to
the deploy to run yarn instead of npm
todo list:
=> feature: add yarn support

python3/deploy, python3/install
with the objective of using venv activate like on python2 platform I have made a modification on python3 platform to use venv on python3.5
Also remove messages about pip cache
=> modify python3 platform to use venv like on python2 platform

nodejs/deploy
The '--prod' flag is making the deploys to randomly fail and the
last versions 0.17.x forces prod mode when 'NODE_ENV=production'.
There's an issue open on the yarn repo (yarnpkg/yarn#1462) about
this problem.
=> nodejs: Fix yarn to the last working version

buildpack/Dockerfile, cordova/Dockerfile, elixir/Dockerfile, go/Dockerfile, java/Dockerfile, lua/Dockerfile, nodejs/Dockerfile, perl/Dockerfile, php/Dockerfile, play/Dockerfile, pypy/Dockerfile, python/Dockerfile, ruby/Dockerfile, static/Dockerfile, tests/Dockerfile.template
This is necessary if we are to change the default user in the base platform.
Also this sets the USER ubuntu in the buildpack dockerfile since it doesn't use the base platform.
=> ensure install scripts run as root

nodejs/deploy, tests/nodejs/tests.bats
PR #50 introduced a bug in nodejs platform. Errors in `yarn install --non-interactive` were being ignored.
=> nodejs: fix yarn install error treatment

static/install
Since the platform uses Ubuntu 14.04, the latest nginx available there
is too old (1.4). Using the ppa, we can get nginx 1.12.
=> static/install: use latest nginx

nodejs/deploy, nodejs/install, tests/nodejs/tests.bats, tests/run.sh
Running nvm with `set -e` causes error messages to be swallowed because
the script exits before the error message is printed. Now we allow
errors while running nvm and only exit after we've handled the error ourselves.
Now the error of a invalid nodejs version looks like:
```
$ tsuru app-deploy . -a myapp
Uploading files (0.00MB)... 100.00% Processing. ok
ERROR: `nvm install ">=v8.9.3"` returned exit status 3.
Version '>=v8.9.3' not found - try `nvm ls-remote` to browse available versions.
error running "/var/lib/tsuru/deploy archive file:///home/application/archive.tar.gz": exit status 3
Exit status 1
```
Related to #54
=> nodejs: improve nvm error handling

python/deploy
While testing sometimes pyenv would not create shims for dependencies
with bins. This is hard to reproduce but forcing a pyenv rehash seems to
work as it'll create all missing shims.
=> python: force pyenv rehash after installing dependencies with pipenv

nodejs/README.md, nodejs/deploy, tests/nodejs/tests.bats
Since #44, `--production` flag is always set in yarn or npm. With this, it ignores `NPM_CONFIG_PRODUCTION` env var and doesn't install dev dependencies.
With this PR, we only set this flag if `NPM_CONFIG_PRODUCTION` env var is undefined. Now it's possible to set `NPM_CONFIG_PRODUCTION=false` to also install dev dependencies.
=> nodejs: ignore production flag when NPM_CONFIG_PRODUCTION env var is set

python/install
This PR allows users of the python platform to use modern versions of the pypy platform, both pypy2 as well as pypy3.
=> Adding pypy2 and pypy3 to python platform

go/install
`source` is a `bash` exclusive builtin. Using `.` make the script
compatible with `sh`.
This fixes the error message `sh: 27: source: not found` during deploys.
=> go: make $HOME/.profile compatible with /bin/sh

nodejs/deploy
If NPM_REGISTRY is set we can make deploys easier by automatically replacing common npm registry paths by the one set in NPM_REGISTRY in both `yarn.lock` and `package-lock.json` files.
=> nodejs: replace registry url in lock files

perl/deploy
The perl platform fails to use the dependencies provided using the `vendor` folder because of a check using `-f` instead of `-d`.
=> perl: fix directory check

python/deploy
setup.py files can specify dependency_links which point to alternative
location for packages. It's useful for legacy deployments on hybrid
environments that contain private packages on private git/hg repos.
This is a deprecated feature that has not been replaced yet ¯\_(ツ)_/¯,
so let's keep using it? x)))
=> python: provide --process-dependency-links to pip install

nodejs/deploy, tests/nodejs/tests.bats
This fixes npm and yarn registry URLs replacement with `$NPM_REGISTRY`.
=> nodejs: fix regexp in deploy script

ruby/deploy, tests/ruby/tests.bats
This may happen for Gemfile.lock files generated with old bundler version. In this case we'll now install bundler based on the chosen ruby version.
=> ruby: install bundler when Gemfile.lock is present with no BUNDLED WITH

python/README.md, python/install
As the title says, this installs the python version 3.7.4 and the dev dependency needed to build `libffi-dev`.
=> python: add support to version 3.7.4

nodejs/deploy, tests/nodejs/tests.bats
Also the default yarn version and yarn version detection were improved
because some old yarn versions would always update files in node_modules
regardless if there were changes to package.json and lock file.
Caches from nvm, npm and yarn are now also cleared.
=> nodejs: Preserve node modules if dependencies were not updated

php/Dockerfile, php/deploy.py, tests/Dockerfile.template, tests/nodejs/tests.bats, tests/php/tests.bats
Previously the generated `Procfile` would belong to the `root` user. This caused problems if the user tried to upload a custom `Procfile` as overwriting it would fail.
=> php: Fix ownership for generated Procfile

go/install
I'm trying to deploy an application using `dep` as dependency management tool.
To setup I need to set a hook in tsuru.yaml file, example:
```
hooks:
build:
- go get github.com/golang/dep/cmd/dep
- dep ensure -v -vendor-only
- go build -o $HOME/app cmd/app/main.go
```
But during the deploy a received an error:
```
remote:  ---> Running "go get github.com/golang/dep/cmd/dep"
remote: go: missing Git command. See https://golang.org/s/gogetcmd
remote: package github.com/golang/dep/cmd/dep: exec: "git": executable file not found in $PATH
```
This pull request have objective add git dependency in golang tsuru base platform, suppporting correctly go get commands.
=> Adding git dependency to support 'go get' command in Go platform.

go/deploy
This prevents files from one Go version from possibly overlapping with files from a new Go version.
This kind of overlapping can happen on some filesystems (namely AUFS) even with the `rm -rf` that was already present. See moby/moby#24309.
=> go: install go versions in different directories

python/deploy, tests/python/tests.bats
Heroku's Python Buildpack migrated to a new S3 bucket. Although the old one is not going to be deleted, it's **not** going to be updated anymore. Also, it doesn't include the latest version, 3.9.
Please check the indivudual commits for additional info.
🎃🍻🥨
=> python: use the new bucket, update versions and add 3.9
